server:
  port: 8081
# rabbitmq配置
spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672
    username: admin
    password: admin
    virtual-host: testhost
    publisher-returns: true
    connection-timeout: 15000
    publisher-confirm-type: correlated
    template:
      mandatory: true
