server:
  port: 8082
# rabbitmq配置
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: admin
    password: admin
    virtual-host: testhost
    connection-timeout: 15000
    listener:
      simple:
        #客户端的签收模式为手动签收，这样我们可以保证消息的可靠性送达，或者再消费端消费失败的时候可以做到重回队列（不建议）、根据业务记录日志等处理
        acknowledge-mode: manual
        #设置监听限制(并发量)：最大10，默认5
        concurrency: 5
        max-concurrency: 10
